UsedVehicles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home_page.urls')),
    path('admin/', admin.site.urls),
    path('register/', include('user_registration.urls')),
    path('user_login/', include('user_login.urls')),
    path('announcement_car/', include('announcement_car.urls')),
    path('image_upload/', include('image_upload.urls')),
    path('search_car/', include('search_car.urls')),
    path('contact_info/', include('contact_info.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# TODO: for deployment handle diferently media files

announcement_car/urls.py
from django.urls import path
from announcement_car import views
from car.views import get_car_models
from image_upload.views import image_rotate
from image_upload.views import image_remove

app_name = 'announcement_car'

urlpatterns = [
    path('add_new_announcement/', views.AnnounceCarView.as_view(), name='announce_car'),
    path('add_new_announcement/model_dropdown_list_options/', get_car_models),
    path('add_new_announcement/image_rotate/', image_rotate),
    path('add_new_announcement/image_remove/', image_remove),
    path('display_announcement/', views.DisplayAnnouncementView.as_view(), name='display_announcement')
]

home_page/urls.py
from django.contrib import admin
from django.urls import path, include
from home_page.views import Home
from car.views import get_car_models

app_name = 'home_page'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('model_dropdown_list_options/', get_car_models),
]

search_car/urls.py
from django.urls import path
from search_car.views import QuickSearch, DetailedSearch
from search_car.views import latest_records

app_name = 'search_car'

urlpatterns = [
    path('quick_search/', QuickSearch.as_view(), name='quick_search'),
    path('detailed_search/', DetailedSearch.as_view(), name='detailed_search'),
    path('latest_records/', latest_records),
]

search_car/models.py
from django.db import models

# Create your models here.

search_car/forms.py
import datetime
from django import forms
from car.models import Brand, Model, BodyType, FuelType, Transmission, Drive, \
                        EmissionClass, Color, AirCondition, CruiseControl, Airbag
from contact_info.models import Region

class QuickSearchForm(forms.Form):
    """ Form for quick car search """
    brand = forms.ModelChoiceField(empty_label = 'Brand...',
            widget=forms.Select, queryset=Brand.objects.all())
    model = forms.ModelChoiceField(required=False, empty_label = 'Model...',
            widget=forms.Select, queryset=Model.objects.all())
    body_type = forms.ModelChoiceField(required=False, empty_label = 'Body type...',
            widget=forms.Select, queryset=BodyType.objects.all())
    price_from = forms.IntegerField(required=False, min_value=0)
    price_to = forms.IntegerField(required=False, min_value=0)
    first_reg_from = forms.IntegerField(required=False,
            min_value=1900, max_value=datetime.datetime.now().year)
    first_reg_to = forms.IntegerField(required=False,
            min_value=1900, max_value=datetime.datetime.now().year)
    km_from = forms.IntegerField(required=False, min_value=0)
    km_to = forms.IntegerField(required=False, min_value=0)
    fuel_type = forms.ModelChoiceField(required=False, empty_label = 'Fuel type...',
            widget=forms.Select, queryset=FuelType.objects.all())
    region = forms.ModelChoiceField(required=False, empty_label = 'Region...',
            widget=forms.Select, queryset=Region.objects.all())

    def __init__(self, *args, **kwargs):
        super(QuickSearchForm, self).__init__(*args, **kwargs)
        fields_list = {'brand': 'Brand',
                        'model': 'Model',
                        'body_type': 'Body type',
                        'price_from': 'Price from',
                        'price_to': 'Price to',
                        'first_reg_from': 'First registration from',
                        'first_reg_to': 'First registration to',
                        'km_from': 'Kilometerage from',
                        'km_to': 'Kilometerage to',
                        'fuel_type': 'FuelType',
                        'region': 'Region'}

        self.fields['model'].widget.attrs['disabled'] = "disabled"

        for key in fields_list:
            self.fields[key].widget.attrs.update({'class': 'form-control'})
            if self.fields[key].widget.input_type == 'number':
                self.fields[key].widget.attrs.update({'placeholder': fields_list[key]})

class DetailedSearchForm(forms.Form):
        """ Form for detailed car search """
        # quick search
        brand = forms.ModelChoiceField(empty_label = 'Brand...',
                widget=forms.Select, queryset=Brand.objects.all())
        model = forms.ModelChoiceField(required=False, empty_label = 'Model...',
                widget=forms.Select, queryset=Model.objects.all())
        body_type = forms.ModelChoiceField(required=False, empty_label = 'Body type...',
                widget=forms.Select, queryset=BodyType.objects.all())
        price_from = forms.IntegerField(required=False, min_value=0)
        price_to = forms.IntegerField(required=False, min_value=0)
        first_reg_from = forms.IntegerField(required=False,
                min_value=1900, max_value=datetime.datetime.now().year)
        first_reg_to = forms.IntegerField(required=False,
                min_value=1900, max_value=datetime.datetime.now().year)
        km_from = forms.IntegerField(required=False, min_value=0)
        km_to = forms.IntegerField(required=False, min_value=0)
        fuel_type = forms.ModelChoiceField(required=False, empty_label = 'Fuel type...',
                widget=forms.Select, queryset=FuelType.objects.all())
        region = forms.ModelChoiceField(required=False, empty_label = 'Region...',
                widget=forms.Select, queryset=Region.objects.all())

        # detailed search
        ccm_from = forms.IntegerField(required=False, min_value=0)
        ccm_to = forms.IntegerField(required=False, min_value=0)
        power_from = forms.IntegerField(required=False, min_value=0)
        power_to = forms.IntegerField(required=False, min_value=0)
        transmission = forms.ModelChoiceField(required=False, empty_label = 'Transmission...',
                widget=forms.Select, queryset=Transmission.objects.all())
        drive = forms.ModelChoiceField(required=False, empty_label = 'Drive...',
                widget=forms.Select, queryset=Drive.objects.all())
        emission_class = forms.ModelChoiceField(required=False, empty_label = 'Emission class...',
                widget=forms.Select, queryset=EmissionClass.objects.all())
        door_num = forms.IntegerField(required=False, min_value=0)
        seats_number = forms.IntegerField(required=False, min_value=0)
        color = forms.ModelChoiceField(required=False, empty_label = 'Color...',
                widget=forms.Select, queryset=Color.objects.all())
        metalic_color = forms.BooleanField(required=False)
        ac = forms.ModelChoiceField(required=False, empty_label = 'AirCondition...',
                widget=forms.Select, queryset=AirCondition.objects.all())
        cruise_ctrl = forms.ModelChoiceField(required=False, empty_label = 'Cruse control...',
                widget=forms.Select, queryset=CruiseControl.objects.all())
        airbags = forms.ModelChoiceField(required=False, empty_label = 'Airbags...',
                widget=forms.Select, queryset=Airbag.objects.all())

        def __init__(self, *args, **kwargs):
            super(DetailedSearchForm, self).__init__(*args, **kwargs)
            fields_list = {'brand': 'Brand',
                            'model': 'Model',
                            'body_type': 'Body type',
                            'price_from': 'Price from',
                            'price_to': 'Price to',
                            'first_reg_from': 'First registration from',
                            'first_reg_to': 'First registration to',
                            'km_from': 'Kilometerage from',
                            'km_to': 'Kilometerage to',
                            'fuel_type': 'FuelType',
                            'region': 'Region',
                            'ccm_from': 'Cubic capacity from',
                            'ccm_to': 'Cubic capacity to',
                            'power_from': 'Power from',
                            'power_to': 'Power to',
                            'transmission': 'Transmission',
                            'drive': 'Drive',
                            'emission_class': 'Emission class',
                            'door_num': 'Door number',
                            'seats_number': 'Seats number',
                            'color': 'Color',
                            'ac': 'AirCondition',
                            'cruise_ctrl': 'Cruise control',
                            'airbags': 'Airbags'}

            self.fields['model'].widget.attrs['disabled'] = "disabled"
            self.fields['metalic_color'].label = 'Metalic'

            for key in fields_list:
                self.fields[key].widget.attrs.update({'class': 'form-control'})
                if self.fields[key].widget.input_type == 'number':
                    self.fields[key].widget.attrs.update({'placeholder': fields_list[key]})

search_car/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from search_car.forms import QuickSearchForm, DetailedSearchForm
from announcement_car.models import CarAnnouncement
from image_upload.models import CarImageUploadModel
from contact_info.models import AnnouncementContactInfo


# Create your views here.
class QuickSearch(View):
    def get(self, request):
        quick_search_form = QuickSearchForm()
        context = {'quick_search_form': quick_search_form}
        return render(request, 'search_car/quick_search.html', context);

    def post(self, request):
        quick_search_form = QuickSearchForm(request.POST);
        if quick_search_form.is_valid():
            q = CarAnnouncement.objects.filter(
                    car__brand = quick_search_form.cleaned_data['brand'])
            if quick_search_form.cleaned_data['model']:
                print('model')
                q = q.filter(car__model = quick_search_form.cleaned_data['model'])
            if quick_search_form.cleaned_data['body_type']:
                print('body_type')
                q = q.filter(car__body_type = quick_search_form.cleaned_data['body_type'])
            if quick_search_form.cleaned_data['price_from']:
                print('price_from')
                q = q.filter(price__gte = quick_search_form.cleaned_data['price_from'])
            if quick_search_form.cleaned_data['price_to']:
                print('price_to')
                q = q.filter(price__lte = quick_search_form.cleaned_data['price_to'])
            if quick_search_form.cleaned_data['first_reg_from']:
                print('first_reg_from')
                q = q.filter(car__first_registration__gte = quick_search_form.cleaned_data['first_reg_from'])
            if quick_search_form.cleaned_data['first_reg_to']:
                print('first_reg_to')
                q = q.filter(car__first_registration__lte = quick_search_form.cleaned_data['first_reg_to'])
            if quick_search_form.cleaned_data['fuel_type']:
                print('fuel_type')
                q = q.filter(car__fuel_type = quick_search_form.cleaned_data['fuel_type'])
            if quick_search_form.cleaned_data['region']:
                print('region')
                q = q.filter(contact_info__region = quick_search_form.cleaned_data['region'])

            images = []
            for record in q:
                images.append(CarImageUploadModel.objects.get(announcement=record, ordinal=0))

            context = {'results': q,
                        'images': images}

        # return redirect(reverse('home_page:home'))
        return render(request, 'search_car/search_results.html', context);

class DetailedSearch(View):
    def get(self, request):
        detailed_search_form = DetailedSearchForm()
        context = {'detailed_search_form': detailed_search_form}
        return render(request, 'search_car/detailed_search.html', context);

    def post(self, request):
        return render(request, 'search_car/detailed_search.html', None);

def latest_records(request):
    # TODO: when and if our db grows use some filter instead of all() !!!
    # TODO: check if images[0] exists
    records = CarAnnouncement.objects.filter(is_active=True).order_by('date_updated').reverse()[0:12]
    images = []
    for record in records:
        images.append(CarImageUploadModel.objects.get(announcement=record, ordinal=0))
    context = {'records': records,
                'images': images}
    return render(request, 'search_car/latest_records.html', context)

templates/search_car/detailed_search.html
<form class="" method="post" action="{% url 'search_car:detailed_search'%}">

  {% csrf_token %}
  <div id="divQuickSearch">
    <div class="form-row">
      <div class="form-group col-md-4">
        {{ detailed_search_form.brand }}
      </div>
      <div class="form-group col-md-4">
        {{ detailed_search_form.model }}
      </div>
      <div class="form-group col-md-4">
        {{ detailed_search_form.body_type }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3">
        {{ detailed_search_form.price_from }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.price_to }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.first_reg_from }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.first_reg_to }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3">
        {{ detailed_search_form.km_from }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.km_to }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.fuel_type }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.region }}
      </div>
    </div>
  </div> <!-- divBasicInfo -->

  <hr>

  <div id="detailed-search">
    <div class="form-row">
      <div class="form-group col-md-3">
        {{ detailed_search_form.ccm_from }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.ccm_to }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3">
        {{ detailed_search_form.power_from }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.power_to }}
      </div>
      <div id="divPowerUnits" class="form-group col-md-3">
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="[hp]" checked>
          <label class="form-check-label" for="inlineRadio1">HP</label>
        </div>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="[kw]">
          <label class="form-check-label" for="inlineRadio2">kW</label>
        </div>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3">
        {{ detailed_search_form.transmission }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.drive }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.emission_class }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3">
        {{ detailed_search_form.door_num }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.seats_number }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.color }}
      </div>
      <div class="form-group col-md-2" id="divMetalic">
        <div class="form-check">
          {{ detailed_search_form.metalic_color }}
          {{ detailed_search_form.metalic_color.label}}
        </div>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3">
        {{ detailed_search_form.ac }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.cruise_ctrl }}
      </div>
      <div class="form-group col-md-3">
        {{ detailed_search_form.airbags }}
      </div>
    </div>
  </div>

  <div class="row search-btn-container">
    <button type="submit" class="btn btn-info search-btn">Search</button>
  </div>

</form>

templates/search_car/latest_records.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  {% load staticfiles %}
  {% load get_image_url %}
  {% load humanize %}

  {% for record in records %}
    <!-- open row -->
    {% if forloop.counter0|divisibleby:3 %}
      <div class="form-row">
    {% endif %}

    <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <img src="{{ images|get_image_url:forloop.counter0 }}" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="announcement-id" style="display:none;">{{ record.id }}</p>
          {{ record.car.brand }}
          {{ record.car.model }}
          {{ record.car.body_type }},
          Price: {{ record.price }}€
          <br>
          Year: {{ record.car.first_registration }},
          Kilometrage: {{ record.car.kilometerage|intcomma }}km
          <br>
          Fuel: {{ record.car.fuel_type }}, Region: {{ record.contact_info.region }}
          <div class="d-flex justify-content-end align-items-center">
            <div class="">
              <small class="text-muted">{{ record.date_updated|naturaltime }}</small>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- close row -->
    <!-- TODO: check this condition -->
    {% if forloop.counter0 == 2 or forloop.counter0|add:-5|divisibleby:3 or forloop.last %}
      </div>
    {% endif %}

  {% empty %}
    <p>Sorry, we couldn't find any new ads</p>
  {% endfor %}


</html>

templates/search_car/quick_search.html
<form class="" method="post" action="{% url 'search_car:quick_search'%}">

  {% csrf_token %}
  <div id="divQuickSearch">
    <div class="form-row">
      <div class="form-group col-md-4">
        {{ quick_search_form.brand }}
      </div>
      <div class="form-group col-md-4">
        {{ quick_search_form.model }}
      </div>
      <div class="form-group col-md-4">
        {{ quick_search_form.body_type }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3">
        {{ quick_search_form.price_from }}
      </div>
      <div class="form-group col-md-3">
        {{ quick_search_form.price_to }}
      </div>
      <div class="form-group col-md-3">
        {{ quick_search_form.first_reg_from }}
      </div>
      <div class="form-group col-md-3">
        {{ quick_search_form.first_reg_to }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3">
        {{ quick_search_form.km_from }}
      </div>
      <div class="form-group col-md-3">
        {{ quick_search_form.km_to }}
      </div>
      <div class="form-group col-md-3">
        {{ quick_search_form.fuel_type }}
      </div>
      <div class="form-group col-md-3">
        {{ quick_search_form.region }}
      </div>
    </div>
  </div> <!-- divBasicInfo -->

  <div class="row search-btn-container">
    <button id="detailed-search-btn" type="button" class="btn btn-link">Detailed search</button>
    <button type="submit" class="btn btn-info search-btn">Search</button>
  </div>

</form>

templates/search_car/search_results.html
{% extends "__base.html" %}
{% load static %}
{% load get_image_url %}
{% load staticfiles %}
{% load humanize %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/search_car/search_results.css' %}">
{% endblock %}

{% block content %}
  <div class="container">
    <div class="jumbotron jumbotron-custom">

      <div class="display-results-container">
        <div class="search-results-container">
          {% for record in results %}
            <div class="card mb-4 shadow-sm">
              <div class="image-container">
                <img src="{{ images|get_image_url:forloop.counter0 }}" class="card-img-top" alt="...">
              </div>
              <div class="card-body">
                <div class="card-row">
                  <div class="card-col-1">
                    <p class="announcement-id" style="display:none;">{{ record.id }}</p>
                    <span id="car-brand">{{ record.car.brand }}</span>
                    <span id="car-model">{{ record.car.model }}</span>
                    <span id="car-body-type">{{ record.car.fuel_type }}</span>
                  </div>
                  <div class="card-col-0">
                    <span id="car-price">{{ record.price }}€</span>
                  </div>
                </div>
                <div class="card-row">
                  Year: {{ record.car.first_registration }}, Kilometrage: {{ record.car.kilometerage|intcomma }}km
                </div>
                <div class="card-row">
                  Body type: {{ record.car.body_type }}, Region: {{ record.contact_info.region }}
                </div>
                <div class="card-row">

                </div>
                <div class="d-flex justify-content-end align-items-center">
                  <div class="">

                    <small class="text-muted">9 mins ago</small>
                  </div>
                </div>
              </div>
            </div>
          {% empty %}
            <p>Sorry, no results found for requested parameters</p>
          {% endfor %}

        </div>
        <div class="detailed-search-container">
          <p>Detailed search</p>
        </div>
      </div>

    </div>
  </div>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script type="text/javascript">
    var display_announcement_url = "{% url 'announcement_car:display_announcement' %}";
  </script>
  <script src="{% static 'js/search_car/search_results.js' %}"></script>
{% endblock %}