UsedVehicles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home_page.urls')),
    path('admin/', admin.site.urls),
    path('register/', include('user_registration.urls')),
    path('user_login/', include('user_login.urls')),
    path('announcement_car/', include('announcement_car.urls')),
    path('image_upload/', include('image_upload.urls')),
    path('search_car/', include('search_car.urls')),
    path('contact_info/', include('contact_info.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# TODO: for deployment handle diferently media files

announcement_car/urls.py
from django.urls import path
from announcement_car import views
from car.views import get_car_models
from image_upload.views import image_rotate
from image_upload.views import image_remove

app_name = 'announcement_car'

urlpatterns = [
    path('add_new_announcement/', views.AnnounceCarView.as_view(), name='announce_car'),
    path('add_new_announcement/model_dropdown_list_options/', get_car_models),
    path('add_new_announcement/image_rotate/', image_rotate),
    path('add_new_announcement/image_remove/', image_remove),
    path('display_announcement/', views.DisplayAnnouncementView.as_view(), name='display_announcement')
]

contact_info/urls.py
from django.urls import path
from contact_info.views import ShowContactInfoView

app_name = 'contact_info'

urlpatterns = [
    path('profile_settings/', ShowContactInfoView.as_view(), name='profile_settings'),
]

home_page/urls.py
from django.contrib import admin
from django.urls import path, include
from home_page.views import Home
from car.views import get_car_models

app_name = 'home_page'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('model_dropdown_list_options/', get_car_models),
]

user_login/urls.py
from django.urls import path
from user_login import views

app_name = 'user_login'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login_view'),
    path('logout/', views.LogoutView.as_view(), name='logout_view')
]

user_registration/urls.py
from django.urls import path
from user_registration import views

app_name = 'user_registration'

urlpatterns = [
    path('', views.RegisterUserView.as_view(), name='register_user_view'),
    path('successful/', views.RegistrationConfirmationView.as_view(), name='reg_confirmation')
]

templates/__base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>
      {% block title %} UsedVehicles {% endblock %}
    </title>

    {% block stylesheets %}
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static "css/styles.css" %}" type="text/css" />
      {% include "_navbar_stylesheets.html" %}
    {% endblock %}


  </head>
  <body>
    <header >
      {% include "_navbar.html" %}
    </header>
    {% block content %}

    {% endblock %}

    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% endblock %}

  </body>
</html>

templates/_navbar.html
<div>
  <nav class="navbar navbar-light navbar-expand-md navigation-clean-button">
    <div class="container"><a class="navbar-brand" href="{% url 'home_page:home' %}">Used vehicles</a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navcol-1">
        <ul class="nav navbar-nav mr-auto">
          <li class="dropdown"><a class="dropdown-toggle nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Buy</a>
            <div class="dropdown-menu" role="menu">
              <a class="dropdown-item" role="presentation" href="{% url 'home_page:home' %}">Cars</a>
              <a class="dropdown-item" role="presentation" href="#">Motorcycles</a>
              <a class="dropdown-item" role="presentation" href="#">Recreational vehicles</a>
            </div>
          </li>
          <li class="dropdown"><a class="dropdown-toggle nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Sell</a>
            <div class="dropdown-menu" role="menu">
              <a class="dropdown-item" role="presentation" href="{% url 'announcement_car:announce_car' %}">Car</a>
              <a class="dropdown-item" role="presentation" href="#">Motorcycle</a>
              <a class="dropdown-item" role="presentation" href="#">Recreational vehicle</a>
            </div>
          </li>
          <li class="nav-item" role="presentation"><a class="nav-link	" href="#">Need help</a></li>
        </ul>
        {% if user.is_authenticated %}
          {% include "_navbar_logged_in.html" %}
        {% else %}
          {% include "_navbar_anonymous.html" %}
        {% endif %}
      </div>
    </div>
  </nav>
</div>

templates/_navbar_anonymous.html
<span class="navbar-text actions">
  <a class="login" href="{% url 'user_login:login_view' %}"> Log In </a>
  <a class="btn btn-light action-button" role="button" href="{% url 'user_registration:register_user_view' %}"> Sign Up </a>
</span>

templates/_navbar_logged_in.html
{% load static %}
<span class="navbar-text actions">
  <ul class="nav navbar-nav mr-auto">
    <li class="dropdown">
      <a class="nav-link" data-toggle="dropdown" aria-expanded="false" href="#"><img src="{% static "img/avatar_2x.png" %}" class="profile-img"></a>
      <div class="dropdown-menu" role="menu">
        <a class="dropdown-item" role="presentation" href="#">My adds</a>
        <a class="dropdown-item" role="presentation" href="{% url 'contact_info:profile_settings' %}">Profile settings</a>
        <hr>
        <a class="dropdown-item" role="presentation" href="{% url 'user_login:logout_view' %}"><strong>Logout</strong></a>
      </div>
    </li>
  </ul>
</span>

templates/_navbar_stylesheets.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/Navigation-with-Button.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/Fixed-navbar-starting-with-transparency1.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/Fixed-navbar-starting-with-transparency.css' %}">